export const TIME_ENTRY_LIST_REQUEST = 'TIME_ENTRY_LIST_REQUEST'
export const TIME_ENTRY_LIST_SUCCESS = 'TIME_ENTRY_LIST_SUCCESS'
export const TIME_ENTRY_LIST_FAIL = 'TIME_ENTRY_LIST_FAIL'

export const TIME_ENTRY_DAILY_LIST_REQUEST = 'TIME_ENTRY_DAILY_LIST_REQUEST'
export const TIME_ENTRY_DAILY_LIST_SUCCESS = 'TIME_ENTRY_DAILY_LIST_SUCCESS'
export const TIME_ENTRY_DAILY_LIST_FAIL = 'TIME_ENTRY_DAILY_LIST_FAIL'
export const TIME_ENTRY_DAILY_LIST_RESET = 'TIME_ENTRY_DAILY_LIST_RESET'

export const TIME_ENTRY_DETAILS_REQUEST = 'TIME_ENTRY_DETAILS_REQUEST'
export const TIME_ENTRY_DETAILS_SUCCESS = 'TIME_ENTRY_DETAILS_SUCCESS'
export const TIME_ENTRY_DETAILS_FAIL = 'TIME_ENTRY_DETAILS_FAIL'

export const TIME_ENTRY_CREATE_REQUEST = 'TIME_ENTRY_CREATE_REQUEST'
export const TIME_ENTRY_CREATE_SUCCESS = 'TIME_ENTRY_CREATE_SUCCESS'
export const TIME_ENTRY_CREATE_FAIL = 'TIME_ENTRY_CREATE_FAIL'
export const TIME_ENTRY_CREATE_RESET = 'TIME_ENTRY_CREATE_RESET'

export const TIME_ENTRY_SUBMIT_REQUEST = 'TIME_ENTRY_SUBMIT_REQUEST'
export const TIME_ENTRY_SUBMIT_SUCCESS = 'TIME_ENTRY_SUBMIT_SUCCESS'
export const TIME_ENTRY_SUBMIT_FAIL = 'TIME_ENTRY_SUBMIT_FAIL'
export const TIME_ENTRY_SUBMIT_RESET = 'TIME_ENTRY_SUBMIT_RESET'

export const TIME_ENTRY_OPEN_REQUEST = 'TIME_ENTRY_OPEN_REQUEST'
export const TIME_ENTRY_OPEN_SUCCESS = 'TIME_ENTRY_OPEN_SUCCESS'
export const TIME_ENTRY_OPEN_FAIL = 'TIME_ENTRY_OPEN_FAIL'
export const TIME_ENTRY_OPEN_RESET = 'TIME_ENTRY_OPEN_RESET'

export const TIME_ENTRY_PROCESS_REQUEST = 'TIME_ENTRY_PROCESS_REQUEST'
export const TIME_ENTRY_PROCESS_SUCCESS = 'TIME_ENTRY_PROCESS_SUCCESS'
export const TIME_ENTRY_PROCESS_FAIL = 'TIME_ENTRY_PROCESS_FAIL'
export const TIME_ENTRY_PROCESS_RESET = 'TIME_ENTRY_PROCESS_RESET'

export const TIME_ENTRY_DELETE_REQUEST = 'TIME_ENTRY_DELETE_REQUEST'
export const TIME_ENTRY_DELETE_SUCCESS = 'TIME_ENTRY_DELETE_SUCCESS'
export const TIME_ENTRY_DELETE_FAIL = 'TIME_ENTRY_DELETE_FAIL'
